container:
  image: ghcr.io/cirruslabs/android-sdk:33
  cpu: 8
  memory: 24G
  kvm: true
check_android_task:
  # execution_lock: OneEmulatorAtATime
  list_versions_script:
    - sdkmanager --list --verbose| grep ^system-images
  # env:
  #  ARCH: x86
  #  matrix:
  #    - API_LEVEL: 28
  #    - API_LEVEL: 29
  #    - API_LEVEL: 30
  # create_device_script:
  #  - sdkmanager "system-images;android-${API_LEVEL};google_apis_playstore;${ARCH}"
  #  - echo no | avdmanager create avd --force -n test_${API_LEVEL} -k "system-images;android-${API_LEVEL};google_apis_playstore;${ARCH}"
  # start_emulator_background_script:
  #   $ANDROID_HOME/emulator/emulator -avd test_${API_LEVEL} -no-audio -no-window -read-only
  # wait_for_emulator_script:
  #  - ./tools/android-wait-for-emulator
  #  - adb shell input keyevent 82
  # disable_animations_script:
  #   - adb shell settings put global window_animation_scale 0.0
  #   - adb shell settings put global transition_animation_scale 0.0
  #  - adb shell settings put global animator_duration_scale 0.0
  check_script:
    - ./gradlew build testGmsDebugUnitTest
  #  - ./gradlew check :app:connectedGmsDebugAndroidTest
  #  - ./gradlew check :app:connectedFDroidDebugAndroidTest
  always:
    build_artifacts:
      path: "app/build/reports/**"

task:
  name: Android Lint
  env:
    JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64

  foo_script:
    - echo java home is set to $JAVA_HOME
    - which java
    - ls /usr/lib/
    - ls /usr/lib/jvm/
    - ls /usr/lib/jvm/java-17-openjdk-amd64
    - ls /usr/lib/jvm/java-1.17.0-openjdk-amd64
  lint_script: ./gradlew lintGmsDebug
  # always:
  #   android-lint_artifacts:
  #     path: "**/reports/lint-results-gmsDebug.xml"
  #     type: text/xml
  #    format: android-lint
