container:
  image: cirrusci/android-sdk:30
  cpu: 8
  memory: 24G
  kvm: true

check_android_task:
  list_versions_script:
    sdkmanager --list --verbose| grep ^system-images
  env:
    API_LEVEL: 30
    TARGET: default
    ARCH: x86_64
  create_device_script:
    - sdkmanager "system-images;android-$API_LEVEL;google_apis;$ARCH"
    - echo no | avdmanager create avd --force -n test -k "system-images;android-$API_LEVEL;google_apis;$ARCH"
  start_emulator_background_script:
    $ANDROID_HOME/emulator/emulator
    -avd test
    -no-audio
    -no-window
  wait_for_emulator_script:
    ./tools/android-wait-for-emulator
    adb shell input keyevent 82
  disable_animations_script: |
    adb shell settings put global window_animation_scale 0.0
    adb shell settings put global transition_animation_scale 0.0
    adb shell settings put global animator_duration_scale 0.0
  check_script:
    ./gradlew check connectedCheck
  always:
    build_artifacts:
      path: "app/build/reports/**"

task:
  name: Android Lint
  lint_script: ./gradlew lintGmsDebug
  always:
    android-lint_artifacts:
      path: "**/reports/lint-results-gmsDebug.xml"
      type: text/xml
      format: android-lint